export const API_METHODS = [
  {
    name: 'agent()',
    signature: 'Reef.agent()',
    description: 'Returns a chainable builder for human-like web interactions: .click(sel).type(sel, val).submit()',
    safetyGated: false,
    example: "Reef.agent().type('#search-input', 'pricing').submit()",
  },
  {
    name: 'executeWorkflow(workflow, options)',
    signature: 'Reef.executeWorkflow(workflow, options)',
    description: 'Executes multi-step JSON/YAML workflows with error handling, step retries, and step callbacks.',
    safetyGated: false,
    example: "Reef.executeWorkflow({ steps: [{ action: 'click', target: '#btn' }] })",
  },
  {
    name: 'act(recordId)',
    signature: 'Reef.act(recordId)',
    description: 'Executes actions by indexed element record ID — clicks buttons, toggles controls, triggers events.',
    safetyGated: true,
    example: "Reef.act('rec_9821')",
  },
  {
    name: 'fillField(recordId, value)',
    signature: 'Reef.fillField(recordId, value)',
    description: 'Fills target input fields programmatically while dispatching proper input/change DOM events.',
    safetyGated: false,
    example: "Reef.fillField('rec_input_1', 'user@domain.com')",
  },
  {
    name: 'getAgentTools()',
    signature: 'Reef.getAgentTools()',
    description: 'Retrieves all actionable DOM elements with valid CSS selectors and bounding boxes for LLM tool use.',
    safetyGated: false,
    example: 'Reef.getAgentTools()',
  },
  {
    name: 'getSession()',
    signature: 'Reef.getSession()',
    description: 'Retrieves current session state snapshot with { id, url, timestamp, pendingActions }.',
    safetyGated: false,
    example: 'Reef.getSession()',
  },
  {
    name: 'navigate(url)',
    signature: 'Reef.navigate(url)',
    description: 'Programmatic client navigation with pending action queue resolution.',
    safetyGated: false,
    example: "Reef.navigate('/docs/api')",
  },
  {
    name: 'back() / forward()',
    signature: 'Reef.back() | Reef.forward()',
    description: 'Browser history stack controls designed for automated AI agent traversal.',
    safetyGated: false,
    example: 'Reef.back()',
  },
  {
    name: 'wait(timeout)',
    signature: 'Reef.wait(timeoutMs)',
    description: 'Pauses agent workflow execution for asynchronous DOM render operations.',
    safetyGated: false,
    example: 'Reef.wait(1500)',
  },
];

export const COMPARISON_DIMENSIONS = [
  { key: 'type', label: 'Architecture Type' },
  { key: 'backend', label: 'Backend Server Needed' },
  { key: 'cost', label: 'Pricing / License' },
  { key: 'privacy', label: 'Query Privacy' },
  { key: 'dom', label: 'Live DOM Extraction' },
  { key: 'fuzzy', label: 'Typo Tolerance' },
  { key: 'indexed', label: 'Inverted Index' },
  { key: 'types', label: 'Semantic Record Schema' },
  { key: 'bm25', label: 'BM25 / TF-IDF Scoring' },
  { key: 'suggest', label: 'Instant Autocomplete' },
  { key: 'stem', label: 'Language Stemming' },
  { key: 'facet', label: 'Faceted Filters' },
  { key: 'serialize', label: 'Index Sharding' },
];

export const COMPARISON_TOOLS = {
  Reef: {
    pinned: true,
    type: { text: 'Client Script', score: 'good' },
    backend: { text: 'None (0 KB)', score: 'good' },
    cost: { text: '$0 / MIT', score: 'good' },
    privacy: { text: '100% Local', score: 'good' },
    dom: { text: 'Yes (Live DOM)', score: 'good' },
    fuzzy: { text: 'Yes (Indexed)', score: 'good' },
    indexed: { text: 'Yes (Inverted)', score: 'good' },
    types: { text: 'Yes (7 Types)', score: 'good' },
    bm25: { text: 'Yes (Configurable)', score: 'good' },
    suggest: { text: 'Yes (Sub-ms)', score: 'good' },
    stem: { text: 'Yes (Opt-in)', score: 'good' },
    facet: { text: 'Yes (Field-level)', score: 'good' },
    serialize: { text: 'Yes (JSON/Bin)', score: 'good' },
  },
  'Fuse.js': {
    type: { text: 'Client Library', score: 'good' },
    backend: { text: 'None', score: 'good' },
    cost: { text: '$0 / MIT', score: 'good' },
    privacy: { text: '100% Local', score: 'good' },
    dom: { text: 'No (Data array)', score: 'bad' },
    fuzzy: { text: 'Yes (Bitap)', score: 'good' },
    indexed: { text: 'No (Full Scan)', score: 'bad' },
    types: { text: 'No Schema', score: 'bad' },
    bm25: { text: 'No BM25', score: 'bad' },
    suggest: { text: 'No', score: 'bad' },
    stem: { text: 'No', score: 'bad' },
    facet: { text: 'No', score: 'bad' },
    serialize: { text: 'Yes', score: 'good' },
  },
  MiniSearch: {
    type: { text: 'Client Library', score: 'good' },
    backend: { text: 'None', score: 'good' },
    cost: { text: '$0 / MIT', score: 'good' },
    privacy: { text: '100% Local', score: 'good' },
    dom: { text: 'No', score: 'bad' },
    fuzzy: { text: 'Yes', score: 'good' },
    indexed: { text: 'Yes (Inverted)', score: 'good' },
    types: { text: 'No', score: 'bad' },
    bm25: { text: 'Yes', score: 'good' },
    suggest: { text: 'Yes', score: 'good' },
    stem: { text: 'Yes', score: 'good' },
    facet: { text: 'Manual', score: 'neutral' },
    serialize: { text: 'Yes', score: 'good' },
  },
  uFuzzy: {
    type: { text: 'Client Library', score: 'good' },
    backend: { text: 'None', score: 'good' },
    cost: { text: '$0 / MIT', score: 'good' },
    privacy: { text: '100% Local', score: 'good' },
    dom: { text: 'No', score: 'bad' },
    fuzzy: { text: 'Yes (Staged)', score: 'good' },
    indexed: { text: 'No (Full Array)', score: 'bad' },
    types: { text: 'No', score: 'bad' },
    bm25: { text: 'No', score: 'bad' },
    suggest: { text: 'No', score: 'bad' },
    stem: { text: 'No', score: 'bad' },
    facet: { text: 'No', score: 'bad' },
    serialize: { text: 'No', score: 'bad' },
  },
  Orama: {
    type: { text: 'Client / Node', score: 'good' },
    backend: { text: 'None (Browser)', score: 'good' },
    cost: { text: '$0 / Apache', score: 'good' },
    privacy: { text: '100% Local', score: 'good' },
    dom: { text: 'No', score: 'bad' },
    fuzzy: { text: 'Yes', score: 'good' },
    indexed: { text: 'Yes', score: 'good' },
    types: { text: 'Typed Schema', score: 'neutral' },
    bm25: { text: 'Yes', score: 'good' },
    suggest: { text: 'Partial', score: 'neutral' },
    stem: { text: 'Yes (Plugin)', score: 'good' },
    facet: { text: 'Yes', score: 'good' },
    serialize: { text: 'Yes', score: 'good' },
  },
  Pagefind: {
    type: { text: 'Static Build', score: 'neutral' },
    backend: { text: 'None (Static)', score: 'good' },
    cost: { text: '$0 / MIT', score: 'good' },
    privacy: { text: 'Local Shards', score: 'good' },
    dom: { text: 'No (Prebuilt)', score: 'bad' },
    fuzzy: { text: 'Yes', score: 'good' },
    indexed: { text: 'Yes (Static)', score: 'good' },
    types: { text: 'No', score: 'bad' },
    bm25: { text: 'Partial', score: 'neutral' },
    suggest: { text: 'Partial', score: 'neutral' },
    stem: { text: 'Yes', score: 'good' },
    facet: { text: 'Yes', score: 'good' },
    serialize: { text: 'Yes', score: 'good' },
  },
  Algolia: {
    type: { text: 'Hosted SaaS', score: 'bad' },
    backend: { text: 'Required', score: 'bad' },
    cost: { text: 'Paid SaaS', score: 'neutral' },
    privacy: { text: 'Remote Server', score: 'bad' },
    dom: { text: 'No', score: 'bad' },
    fuzzy: { text: 'Yes', score: 'good' },
    indexed: { text: 'Yes', score: 'good' },
    types: { text: 'No', score: 'bad' },
    bm25: { text: 'Custom Rank', score: 'good' },
    suggest: { text: 'Yes', score: 'good' },
    stem: { text: 'Yes', score: 'good' },
    facet: { text: 'Yes', score: 'good' },
    serialize: { text: 'N/A (Cloud)', score: 'bad' },
  },
};

export const FAQS = [
  {
    id: 'frameworks',
    question: 'Does Reef require React, Vue, or a specific build step?',
    answer: 'No. Reef is a self-contained, plain JavaScript tag (<script src="reef.min.js"></script>). It operates directly on standard HTML DOM nodes or sitemaps. If you use SPAs (React, Next.js, Vue, Svelte), Reef listens to pushState/replaceState history events and re-indexes instantly.',
  },
  {
    id: 'server',
    question: 'Do I need a backend server, database, or API keys?',
    answer: 'No. Tokenization, inverted indexing, fuzzy Levenshtein calculations, and BM25 scoring run 100% locally inside the visitor browser thread or background Web Worker. Zero external network calls occur after the initial script load.',
  },
  {
    id: 'privacy',
    question: 'What happens to what visitors search for?',
    answer: 'Nothing is sent anywhere. Search queries never leave the visitor browser memory space. There are zero tracking pixels, telemetry pings, or central servers.',
  },
  {
    id: 'bundle',
    question: 'How large is the bundle size?',
    answer: 'Reef is compressed to ~90 KB uncompressed (~28 KB gzipped) with zero external dependencies.',
  },
  {
    id: 'agentic',
    question: 'What is the Agentic API and actionsMode safety gating?',
    answer: 'Reef exposes window.Reef methods like .act(id), .fillField(id, val), and .getAgentTools(). This allows LLM agents (e.g. Gemini, Anthropic, OpenAI tools) to navigate, fill forms, and interact with static pages safely. Destructive actions (like form submissions or checkout buttons) require explicitly setting data-actions-mode="unrestricted".',
  },
];

export const SEARCH_ITEMS = [
  {
    id: 's1',
    section: 'CRAWL',
    title: 'Client-Side Page & Sitemap Crawler',
    description: 'Reef automatically parses page markup and sitemap.xml files upon script initialization.',
    type: 'CONCEPT',
    codeSnippet: '<script src="reef.min.js" data-sitemap="sitemap.xml"></script>',
  },
  {
    id: 's2',
    section: 'API',
    title: 'Reef.agent() Chainable Interaction Builder',
    description: 'Chain user or LLM agent interactions cleanly with type, click, and submit primitives.',
    type: 'API',
    codeSnippet: "Reef.agent().type('#search', 'BM25').submit()",
  },
  {
    id: 's3',
    section: 'API',
    title: 'Reef.act(recordId) - Direct Element Execution',
    description: 'Triggers action handlers attached to indexed DOM element record IDs.',
    type: 'API',
    codeSnippet: "Reef.act('rec_button_submit')",
  },
  {
    id: 's4',
    section: 'API',
    title: 'Reef.getAgentTools() - DOM Selector Map',
    description: 'Generates a clean JSON dictionary of actionable controls with coordinates and selectors.',
    type: 'API',
    codeSnippet: 'const tools = Reef.getAgentTools();',
  },
  {
    id: 's5',
    section: 'COMPARE',
    title: 'Reef vs Fuse.js & MiniSearch Comparison',
    description: 'Inverted index performance matrix comparing local client-side search tools.',
    type: 'COMPARE',
  },
  {
    id: 's6',
    section: 'INSTALL',
    title: 'Script Tag & Manual Download Options',
    description: 'Include Reef in any HTML file with a single script tag or download reef.min.js.',
    type: 'INSTALL',
    codeSnippet: '<script src="https://reef.js.org/dist/reef.min.js"></script>',
  },
  {
    id: 's7',
    section: 'FAQ',
    title: 'Privacy and Network Security Guarantees',
    description: 'Zero telemetry, zero external database pings, 100% local browser execution.',
    type: 'FAQ',
  },
];
